SIMD-108: Transaction size fee
solana-foundation/solana-improvement-documents pull request #108
Opened 2024-01-18 13:14 UTC by joncinque

The small size of transasctions on Solana can limit how much users can do on the network atomically, forcing apps to do unsafe things such as signing multiple transactions with the assumption that they can be executed serially.

Before we can increase the maximum transaction size, however, the network needs an economic backstop to make sure that validators are properly compensated in the case that large transactions negatively impact transaction throughput or bandwidth usage.

This proposal only covers the economic backstop by including a new fee based on transaction size. It includes the motivation for the fee along with proposed parameters for a safe initial iteration.

2024-01-24 14:31 UTC, aeyakovenko commented
The system should handle more bandwidth in fewer larger txs. I am not sure the super linear component makes sense.

2024-01-24 18:20 UTC, aeyakovenko commented
Wouldn't just accounting for CUs used from the larger txs be enough? Then priority fees will handle the rest.

2024-01-24 18:40 UTC, aeyakovenko commented on proposals/0108-transaction-size-fee.md
> +As with other fees, half of the fee is burned, and half goes to the leader.
this breaks prioritization.  should leaders do priority * CUs + 1/2 * base + 1/2 * tx size / CUs as the priority function?

the fee doesn't make sense and is out of the blue tbh.  it should just be a CU modifier based on benchmarks.

2024-01-24 18:40 UTC, aeyakovenko requested changes
fee doesn't make sense with the prioritization model, should be a CU modifier based on benchmarks

2024-01-24 22:43 UTC, tao-stones commented on proposals/0108-transaction-size-fee.md
> +consumes bandwidth.
From the perspective of evaluating "resources consumed by transaction", transaction byte size correlates to network ingress/egress cost, and separately long term storage cost. 

I was thinking alone [the line ](https://gist.github.com/tao-stones/6fc77b477d1b946db98e8fe8e3e005ee) that transaction base fee (or its total static fee) accounts for all resources used (including CPUs, memory etc). The cost of bandwidth and ledger storage can all be folded into `CU`. 

(now I caught up with Discord discussion about CU :) I still in fav of pricing everything in CU - perhaps in a different name, that better implies "it takes this amount computing power to do xyz".

2024-01-24 22:43 UTC, tao-stones commented on proposals/0108-transaction-size-fee.md
> +Given `total_transaction_bytes` and the fee parameters
Assume `total_transaction_bytes` is cheaply available to validators after deserializing?

2024-01-24 22:43 UTC, tao-stones commented on proposals/0108-transaction-size-fee.md
> +```
+1 for being deterministic, so it can be calculated once then stored for later use

2024-01-26 00:22 UTC, joncinque commented
Thanks for your feedback and discussion everyone. It seems like it makes the most sense to fold this into the CU model since that's the only way to prioritize transactions at the moment. I'll go back to do some testing and propose a CU-based model for the cost. Closing this in the meantime.

2024-01-26 00:22 UTC, closed without merging

2024-03-15 22:26 UTC, aeyakovenko commented
@joncinque i had a recent shower thought on this.  The model should both, add to CUs as best we can as an approximation, and also have a watermark which can't be exceeded.  So similar to the watermark for CUs per account

2025-02-11 17:43 UTC, bw-solana commented
Need to revive something like this.
Replay is network bound.
Today, a txs number of bytes is arguably more important than what's inside the tx.
Large tx does not necessarily imply high CU count (or deserialization of input data does not cost enough).

2025-05-24 15:43 UTC, natalejoeraco1 commented on proposals/0108-transaction-size-fee.md
> +```
Thanks

2025-05-24 15:44 UTC, natalejoeraco1 commented on proposals/0108-transaction-size-fee.md
> +Given `total_transaction_bytes` and the fee parameters
![export-blocks-1738806427744.csv](https://github.com/user-attachments/files/20427061/export-blocks-1738806427744.csv)