Proposal Listing Proof of Concept
solana-foundation/solana-improvement-documents pull request #36
Opened 2023-02-10 01:05 UTC by jamesrp13

@jacobcreech here's a proof of concept for linting. Haven't gotten around to any kind of refactoring and testing or adding it as a Github workflow, but if you `npm run lint` locally on this you'll see that it runs the linter on everything in the `proposals` directory and shows errors for not matching header structure and frontmatter. Not where I want it to be but maybe an okay starting place.

2023-03-05 04:51 UTC, hydrogenbond007 commented
hey @jamesrp13 , do you have any md file explaining it a little bit(wanted to learn more about it)? btw trent recommended working on the proposal before the code https://github.com/solana-foundation/solana-improvement-documents/issues/34

2023-03-05 04:52 UTC, hydrogenbond007 requested changes
hey @jamesrp13 , do you have any md file explaining it a little bit(wanted to learn more about it)? btw trent recommended working on the proposal before the code https://github.com/solana-foundation/solana-improvement-documents/issues/34

2023-03-05 04:56 UTC, jacobcreech commented
@hydrogenbond007 this is not a proposal but an attempt to automate some of the janitorial duties. I'm building off this to create ci for some of the basic proposal checks

2023-03-05 15:42 UTC, hydrogenbond007 commented
oh gotcha 😅

2023-03-08 22:49 UTC, jacobcreech commented
Closing to push in a separate PR

2023-03-08 22:49 UTC, closed without merging